middleware:
  index:
    onStartup: true

vivo:
  triplestore:
    type: TDB
    directory: /data/openvivo

spring:
  data:
    rest:
      # CAUTION: leaving this on will permit all requests from localhost, breaks various UI requests and SSR
      authorize-hal-browser: true
    solr:
      host: http://solr:8983/solr
  devtools:
    restart:
      enabled: true
  h2:
    console:
      enabled: true
  profiles:
    active: dev
